# Module: NumPy Assignments
## Lesson: NumPy
### Assignment 1: Array Creation and Manipulation

1. Create a NumPy array of shape (5, 5) filled with random integers between 1 and 20. Replace all the elements in the third column with 1.
2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Replace the diagonal elements with 0.

### Assignment 2: Array Indexing and Slicing

1. Create a NumPy array of shape (6, 6) with values from 1 to 36. Extract the sub-array consisting of the 3rd to 5th rows and 2nd to 4th columns.
2. Create a NumPy array of shape (5, 5) with random integers. Extract the elements on the border.

### Assignment 3: Array Operations

1. Create two NumPy arrays of shape (3, 4) filled with random integers. Perform element-wise addition, subtraction, multiplication, and division.
2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Compute the row-wise and column-wise sum.

### Assignment 4: Statistical Operations

1. Create a NumPy array of shape (5, 5) filled with random integers. Compute the mean, median, standard deviation, and variance of the array.
2. Create a NumPy array of shape (3, 3) with values from 1 to 9. Normalize the array (i.e., scale the values to have a mean of 0 and a standard deviation of 1).

### Assignment 5: Broadcasting

1. Create a NumPy array of shape (3, 3) filled with random integers. Add a 1D array of shape (3,) to each row of the 2D array using broadcasting.
2. Create a NumPy array of shape (4, 4) filled with random integers. Subtract a 1D array of shape (4,) from each column of the 2D array using broadcasting.

### Assignment 6: Linear Algebra

1. Create a NumPy array of shape (3, 3) representing a matrix. Compute its determinant, inverse, and eigenvalues.
2. Create two NumPy arrays of shape (2, 3) and (3, 2). Perform matrix multiplication on these arrays.

### Assignment 7: Advanced Array Manipulation

1. Create a NumPy array of shape (3, 3) with values from 1 to 9. Reshape the array to shape (1, 9) and then to shape (9, 1).
2. Create a NumPy array of shape (5, 5) filled with random integers. Flatten the array and then reshape it back to (5, 5).

### Assignment 8: Fancy Indexing and Boolean Indexing

1. Create a NumPy array of shape (5, 5) filled with random integers. Use fancy indexing to extract the elements at the corners of the array.
2. Create a NumPy array of shape (4, 4) filled with random integers. Use boolean indexing to set all elements greater than 10 to 10.

### Assignment 9: Structured Arrays

1. Create a structured array with fields 'name' (string), 'age' (integer), and 'weight' (float). Add some data and sort the array by age.
2. Create a structured array with fields 'x' and 'y' (both integers). Add some data and compute the Euclidean distance between each pair of points.

### Assignment 10: Masked Arrays

1. Create a masked array of shape (4, 4) with random integers and mask the elements greater than 10. Compute the sum of the unmasked elements.
2. Create a masked array of shape (3, 3) with random integers and mask the diagonal elements. Replace the masked elements with the mean of the unmasked elements.

In [2]:
import numpy as np

### Assignment # 1

In [3]:
np.random.randint(1,21, size= (5,5))

array([[12, 20,  6, 14,  1],
       [17, 13, 12,  4,  7],
       [ 9, 11, 19, 11, 15],
       [ 3, 13,  1, 11,  1],
       [ 2,  7, 10,  4, 15]], dtype=int32)

In [4]:
arr = np.arange(1,17).reshape(4,4)
print(arr)
rand = 0
for i in arr:
    i[rand] = 0
    rand+=1
print(arr)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
[[ 0  2  3  4]
 [ 5  0  7  8]
 [ 9 10  0 12]
 [13 14 15  0]]


### Assignment # 2

In [5]:
arr = np.arange(1,37).reshape(6,6)
print("Original Array: \n", arr)

sub_arr = arr[2:5,2:5]
print("Sub-Array: \n", sub_arr)

Original Array: 
 [[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]
 [31 32 33 34 35 36]]
Sub-Array: 
 [[15 16 17]
 [21 22 23]
 [27 28 29]]


In [6]:
arr = np.random.randint(1,25,size = (5,5))
print("arr: \n", arr)
print()
print("First row: \n",arr[0])
print("Last row: \n",arr[-1])

print("First column: ")
l = []
for i in arr:
    l.append(int(i[0]))
print(l)

print("Second column: ")
j = []
for i in arr:
    j.append(int(i[-1]))
print(j)

arr: 
 [[19 11 11 11 24]
 [12 10 10 19  9]
 [24 11 16  9  3]
 [17 13 19 20  6]
 [11  2 20 18 24]]

First row: 
 [19 11 11 11 24]
Last row: 
 [11  2 20 18 24]
First column: 
[19, 12, 24, 17, 11]
Second column: 
[24, 9, 3, 6, 24]


### Assignment # 3

<!-- 1. Create two NumPy arrays of shape (3, 4) filled with random integers. Perform element-wise addition, subtraction,
multiplication, and division.
2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Compute the row-wise and column-wise sum. -->

In [7]:
# 1. Create two NumPy arrays of shape (3, 4) filled with random integers. Perform element-wise addition, subtraction,
# multiplication, and division.
# 2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Compute the row-wise and column-wise sum.
arr1 = np.random.randint(1,10,size = (3,4))
arr2 = np.random.randint(10,20,size = (3,4))
print("Addition: \n", arr1+arr2)
print("Subtraction: \n", arr1-arr2)
print("Division: \n", arr1/arr2)
print("Multiplication: \n", arr1*arr2)

Addition: 
 [[23 18 22 24]
 [21 15 27 23]
 [28 14 23 22]]
Subtraction: 
 [[-11  -2 -16  -6]
 [ -3  -9  -9 -13]
 [-10 -12  -9 -10]]
Division: 
 [[0.35294118 0.8        0.15789474 0.6       ]
 [0.75       0.25       0.5        0.27777778]
 [0.47368421 0.07692308 0.4375     0.375     ]]
Multiplication: 
 [[102  80  57 135]
 [108  36 162  90]
 [171  13 112  96]]


In [8]:
arr = np.arange(1,17).reshape(4,4)
print("arr: \n", arr)
print("row wise sum:")
for i in range(len(arr)):
    sum_ = 0
    for j in arr[i]:
        sum_+=j
    print(f"The sum of {i+1} row is: ", sum_)

print("\ncolumn wise sum:")
for i in range(len(arr)):
    sum_ = 0
    for j in arr:
        sum_+=j[i]
    print(f"The sum of {i+1} column is: ", sum_)

arr: 
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
row wise sum:
The sum of 1 row is:  10
The sum of 2 row is:  26
The sum of 3 row is:  42
The sum of 4 row is:  58

column wise sum:
The sum of 1 column is:  28
The sum of 2 column is:  32
The sum of 3 column is:  36
The sum of 4 column is:  40


### Assignment # 4

In [9]:
arr = np.random.randint(1,11,size = (5,5))
print("Mean: ", np.mean(arr))
print("Median: ", np.median(arr))
print("Standard Deviation: ", np.std(arr))
print("Variance: ", np.var(arr))

Mean:  5.12
Median:  4.0
Standard Deviation:  3.063592662218657
Variance:  9.3856


In [10]:
arr= np.arange(1,10).reshape(3,3)
mean = np.mean(arr)
std = np.std(arr)
normalized_arr = (arr - mean) / std
normalized_arr

array([[-1.54919334, -1.161895  , -0.77459667],
       [-0.38729833,  0.        ,  0.38729833],
       [ 0.77459667,  1.161895  ,  1.54919334]])

### Assignment # 5


In [11]:
arr = np.random.randint(1,11,size =(3,3))
ID = np.random.randint(1,11,size =(3,))
print("Arr: \n", arr)
print("ID: \n", ID)
for i in range(len(arr)):
    arr[i] = arr[i]+ID
print("After addition: \n",arr)

Arr: 
 [[10  3  1]
 [ 3  4  6]
 [ 4  2  9]]
ID: 
 [ 6  4 10]
After addition: 
 [[16  7 11]
 [ 9  8 16]
 [10  6 19]]


In [12]:
arr = np.random.randint(1,11,size =(4,4))
ID = np.random.randint(1,11,size =(4,))
print("Arr: \n", arr)
print("ID: \n", ID)
for i in range(len(arr)):
    arr[i] = arr[i]-ID
print("After subtraction: \n",arr)

Arr: 
 [[9 2 6 8]
 [9 4 1 2]
 [7 8 7 2]
 [1 7 5 7]]
ID: 
 [8 8 4 6]
After subtraction: 
 [[ 1 -6  2  2]
 [ 1 -4 -3 -4]
 [-1  0  3 -4]
 [-7 -1  1  1]]


### Assignment # 6

In [15]:
arr = np.random.randint(1,11,size =(3,3))
print("Determinant: \n", np.linalg.det(arr))
print("inverse: \n", np.linalg.inv(arr))
print("eigenvalues: \n", np.linalg.eig(arr))

Determinant: 
 -571.0000000000001
inverse: 
 [[ 0.01576182  0.11033275 -0.02977233]
 [ 0.12784588 -0.10507881 -0.01926445]
 [-0.13485114  0.05604203  0.14360771]]
eigenvalues: 
 EigResult(eigenvalues=array([17.95538716,  5.66159169, -5.61697885]), eigenvectors=array([[ 0.61146822,  0.31240227,  0.50358415],
       [ 0.40476932,  0.20520404, -0.79038423],
       [ 0.67990324, -0.92752149,  0.34884921]]))


In [14]:
arr1 = np.random.randint(1,11,size =(3,3))
arr2 = np.random.randint(1,11,size =(3,3))
print(arr1*arr2)

[[20 32  2]
 [48 60 48]
 [ 6  7 21]]


### Assignment # 7

In [ ]:
np.arange(1,10).reshape(3,3).reshape(1,9).reshape(9,1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [19]:
arr = np.arange(1,26).reshape(5,5)
arr.flatten().reshape(5,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])